#!/bin/bash

# Usage: varycachelinesize 16 64 for powers of two from 16 to 64 inclusive
# IMPORTANT: Line sizes of 128 or larger crash the simulator!

for ((cache_linesize = $1; cache_linesize <= $2; cache_linesize *= 2))
do
  echo -n "D1_cache_linesize,$cache_linesize"
  export SSFLAGS="-cache:dl1 dl1:1024:$cache_linesize:1:l"
  ./run-wattch 2>&1 | ./scripts/tabulate
done
